// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    baseurl: "https://reqres.in",
    value: "2"
  }
});

export default function() {
  postman[Request]({
    name: "Get User Data",
    id: "2bec3733-c9b5-40ae-8ef1-b93957f3a925",
    method: "GET",
    address: "{{baseurl}}/api/users?page={{value}}"
  });
}
